### ISSUE TITLE
Android MediaMetadataRetriever Performance

### ISSUE THREAD

**Issue by hashimks** [inthehand/InTheHand.Forms#11]
Hello,

I just tried this plugin in Xamarin. I have an issue here.  I am showing a list of videos on a page and selecting it needs to show the video page. Here the problem is when I tried to select it, the next page navigation is taking long as it is trying to load the video which is causing issues. Is there anything we can do here to navigate page fast and the video plays on clicking the play button.

**Comment by peterfoot** [comment]
How/when are you setting the source for the MediaElement? Is the issue on a single platform or across multiple platforms?

**Comment by danieltabarest** [comment]
the same issue, when loading a next page navigation is taking long, some new result with this issue

**Comment by closetoyou293** [comment]
I had performance issue in Android. It takes 20-30 seconds to show video. My project uses Xamarin Form.

**Comment by peterfoot** [comment]
Where is the source video file, what kind of Uri are you using?

**Comment by danieltabarest** [comment]
Hey @peterfoot I am using on the xaml this code, I am using the a video example
<forms:MediaElement HorizontalOptions="Fill" BackgroundColor="Green" VerticalOptions="Center" HeightRequest="180" x:Name="Media" IsLooping="True"  AreTransportControlsEnabled="true" Source="http://video.ch9.ms/ch9/334f/891b78a5-642d-40b4-8d02-ff40ffdd334f/LoginToLinkedinUSingXamarinAuth_mid.mp4"/>

But it takes a lot of time to show the video

**Comment by closetoyou293** [comment]
It seems loading metadata is a problem. 
It takes 1-2 second to set uri into MediaMetadataRetriever and 6-7 second to extract metadata.

**Comment by peterfoot** [comment]
Looking into this, the metadata is required in order to get the video frame size so either needs performance resolving or running this in a separate thread which can then update the video stretch when retrieved...

**Comment by peterfoot** [comment]
MediaMetadataRetriever now runs in background thread to avoid blocking the UI.
