### ISSUE TITLE
Android: MediaElement.Source crash

### ISSUE THREAD

**Issue by RonnyCoder** [inthehand/InTheHand.Forms#12]
I want to play audio file. First, I am recording audio and then wanted to play it. For iOS and Windows its working perfectly fine but for android its crashing.  Source - address of file. 
Can you please help me out.

crashing at  _view.SetVideoURI(global::Android.Net.Uri.Parse(Element.Source.ToString()));
Do I need to create renderer ?

**Comment by RonnyCoder** [comment]
FYI , 
**Source**  path =  _/data/data/MyProject.Android/files/97a6d9e3-0ad3-47c3-818f-f264efd8abcc.wav_
mediaElement.Source = new Uri(path);

Result: 
System.ArgumentNullException has been thrown
Value cannot be null.
Parameter name: String

**Comment by mwpb** [comment]
In case it helps, here is an example which also crashes for Android with NuGet package 1.0.2017.804:

https://github.com/mwpb/InTheHandSetPosition

it worked ok with the previous NuGet package.

I don't have access to my testing devices right now, but I think that to reproduce the crash one should click 'Load Video'. I think if you look at the stack trace there are some paths that shouldn't be there.

**Comment by peterfoot** [comment]
Fixed in 1.2017.810 source and NuGet

**Comment by mwpb** [comment]
Thanks: can confirm this works for the sample project above.

**Comment by RonnyCoder** [comment]
Thanks

**Comment by tonyleone1964** [comment]
we use the 810...and i have this situation:

android 6.0 with this url: https://mnmedias.api.telequebec.tv/m3u8/29880.m3u8 - result crash
windows 10 uwp - dont crash but dont play the video only first frame

with this url:
http://techslides.com/demos/sample-videos/small.mp4

win10 uwp-ok
android 6.0 - ok
android 5.0 - crash

the inthehand.form support hls ? wich format type can i use for uwp, android and ios ?
