### ISSUE TITLE
FullScreen Option in Android

### ISSUE THREAD

**Issue by arivera12** [inthehand/InTheHand.Forms#14]
I don't see the FullScreen option on the media player is this implemented? I can't check this yet on iOS but in Android there is no FullScreen options being displayed. My source is from the sample.
[Sample Source](https://github.com/inthehand/InTheHand.Forms/blob/master/MediaPlayerSample/MediaPlayerSample/MainPage.xaml)

**Comment by dationguyen** [comment]
+1
i am facing the same problem.

**Comment by SMSteve** [comment]
+1

**Comment by JohnGalt1717** [comment]
+1

**Comment by stephenmante** [comment]
+1

**Comment by peterfoot** [comment]
Looking into this. The Android implementation looks a little trickier since we have to place the control fullscreen and also control the statusbar etc for the running activity. iOS and Windows have built in support in the native control.

**Comment by returnZro** [comment]
i am facing the same problem too

**Comment by peterfoot** [comment]
All future MediaElement work will take place at https://github.com/xamarin/XamarinCommunityToolkit
