### ISSUE TITLE
Video not playing

### ISSUE THREAD

**Issue by hashimks** [inthehand/InTheHand.Forms#15]
Hello I have taken a low compression video using Plugin.Media and uploaded to S#

https://s3.amazonaws.com/hashimsbucket/5131484024127625850bd.mov

When i try to play this video in Android mobiles and iOS simulator, it is playing. However I am not able to play this video in iOS devices? It is showing like below. Can you please help me resolve this?

![6ca4b554448e3a4f78a83c490fe928a22fda46a126a3f38cbe pimgpsh_thumbnail_win_distr](https://user-images.githubusercontent.com/30616681/29823324-efc84dc0-8ceb-11e7-93ec-4f8e21b2a7aa.jpg)

**Comment by hashimks** [comment]
@peterfoot Hello is there anything you found out? I guess its the probelm with video's audio which is AMR narrow band... does this player supports AMR audio?

**Comment by peterfoot** [comment]
What version of iOS are you running it on? According to the Apple docs AMR should be supported for playback on iOS but not for recording. The MediaElement will support any codecs the OS supports since it uses the AVPlayer API on iOS.

**Comment by hashimks** [comment]
Hello.. i have actually taken this video from an android device where the recorded video is this and the same is stored in S3. This video then I tried to access in iOS with this player  and not able to play. I am running iOS 10.2

**Comment by hashimks** [comment]
@peterfoot Hello.. it was the problem with device codec. Not an issue with the player. I am closing this. Thanks
