### ISSUE TITLE
MediaElement - Add UWP support for HTTP headers

### ISSUE THREAD

**Issue by peterfoot** [inthehand/InTheHand.Forms#18]

**Comment by JohnGalt1717** [comment]
Please also add the same for Android. This is required to play back Azure Media Services JWT token encrypted videos. (ios has an ugly hack because of it's failure to implement standards correctly)

**Comment by peterfoot** [comment]
The Android control already supports the HttpHeaders property, it's just the UWP renderer they are currently missing from.

**Comment by JohnGalt1717** [comment]
Great! How does one reference it from the shared library?

**Comment by peterfoot** [comment]
Something like this assuming your control has an x:Name of MediaPlayer
MediaPlayer.HttpHeaders.Add("header-name","value");

These must be set prior to setting the Source property.

**Comment by peterfoot** [comment]
All future MediaElement work will take place at https://github.com/xamarin/XamarinCommunityToolkit
