### ISSUE TITLE
Play Local Files?

### ISSUE THREAD

**Issue by developer04** [inthehand/InTheHand.Forms#20]
Hello,

This is a question,

Does Media Player support Local Files? 
if I storage a video from an url can I play it offline?

regards

**Comment by charlesroddie** [comment]
Yes it supports both web links and local files.

**Comment by developer04** [comment]
Thanks for the quick answer. 

I actually download the video from tue url and save it in a byte[]. Is that the correct way to storage for play then local? or can you sugest the correct way please.

regards

**Comment by charlesroddie** [comment]
save as a file and give the path

**Comment by sbal434** [comment]
Hi there, just following up to this, how exactly will the Source variable look like for local files? Specifically, if that file has been added to the shared class of a Xamarin Forms app.

**Comment by peterfoot** [comment]
If the file is part of the app package e.g. Resources/raw for Android then you can use ms-appx::/// followed by the filename. If it is part of the applications data you can pass either the full path as a file:/// Uri or the local path as a ms-appdata:/// Uri. The two ms-* schemes were added for cross-platform use and compatibility with UWP but we may introduce new schemas for these two "special" locations in the future.

**Comment by developer04** [comment]
It works perfectly, thank you!

**Comment by noahjerreel** [comment]
Yes, it works also on my end. Thank you for this.
