### ISSUE TITLE
MediaElement doesn't work in IOS

### ISSUE THREAD

**Issue by hectorast** [inthehand/InTheHand.Forms#21]
I have install InTheHand Nudget version 1.0.2017.712 due to Xaml.Forms version (I have install version 2.3.4.224) and I cannot upgrade Xaml.Forms due to proyect requeriments.
When I tried to add MediaElement in the View, in Android works but in IOS only show BackgroundColor defined.

Any solutions?

Thank you.

**Comment by peterfoot** [comment]
I've not seen this and would need more detail - what kind of source Uri are you using? Although the NuGet depends on Xamarin.Forms 2.3.4.247 this is only a bugfix update from 224 so I'd recommend updating it so you can get the latest version (1.0.2017.1021)

**Comment by jelle-vdst** [comment]
I'm exeriencing the same issue, working with the latest nuget version. Uwp and android both work fine, IOS only shows the BackgroundColorDefined. I'm using the same uri used in the example app. The issue occures on both IOS emulators i've tried (iphone 8 and iphone x both using IOS11), i haven't been able to test it on a real device yet.

**Comment by jelle-vdst** [comment]
I've tested it on a real device and the problem still persists

**Comment by jelle-vdst** [comment]
Found what was causing the problem for me.

I still needed to manually add following line of code to the FinishedLaunching method in IOS
InTheHand.Forms.Platform.iOS.InTheHandForms.Init();

**Comment by dationguyen** [comment]
InTheHand.Forms.Platform.iOS.InTheHandForms.Init(); solve this issue
