### ISSUE TITLE
Can't play this video after recent vs and xamarin update

### ISSUE THREAD

**Issue by Reza-Mortazavi** [inthehand/InTheHand.Forms#27]
I'm not sure if this is the real reason or not but I tried the package for the first time with exact sample code and default media link after installing recent updates for vs 2017 and Xamarin forms and I get message "Can't play this video" while I can open the media with PC web browser but not emulator's browser.

1. What extensions and codecs are supported as streamed video?
2. What are the minimum supported Android and iOS versions?
3. What could be possible solution to fix this playback problem?

Thanks in advanced

**Comment by peterfoot** [comment]
Are you using Xamarin Forms 2.5? if so this could be related to another issue raised for that...

**Comment by Reza-Mortazavi** [comment]
Shared Project
Xamarin Forms 2.5.0.91635 in VS 2017 
min Android version 4.1 compiled by Android 8 - emulator 8
using InTheHand.Forms source, not Package

My first experience with movies on Xamarin and after this post, I found out this maybe something related to emulator limitations, ie, emulator may fail to show the movie but same movie with same code can be played on actual device.
A little bit short on time now, I'll try to check this out ASAP and let you know. meanwhile, I appreciate if you provide me some info on that issue or at least a clue.

Thank you

**Comment by peterfoot** [comment]
The emulators may not have all the Codecs required and so playback should be confirmed on a real device. I'm investigating a compatibility issue with Forms 2.5, they've probably changed something in the renderers which has broken something
