### ISSUE TITLE
Xamarin Forms 2.5 support?

### ISSUE THREAD

**Issue by jelle-vdst** [inthehand/InTheHand.Forms#29]
I was wondering if the new 2.5 release is supported?
I have you're nuget package perfectly working before 2.5, but it's not working after upgrading.
(I haven't yet been able to determine the exact cause of the issue, might also be a xamarin bug ofcourse) 

UPDATE: ios & android still working, only uwp has a problem

**Comment by peterfoot** [comment]
Investigating compatibility

**Comment by ozzy1873** [comment]
I also have a problem on UWP after upgrading with the control crashing the app upon instantiation of the page on which it is embedded.

**Comment by joseluisct** [comment]
I think I have same problem on UWP after upgrading. My exception is:

System.IO.FileNotFoundException: Could not load file or assembly 'InTheHand.Forms, Version=10.2018.0.0, Culture=neutral, PublicKeyToken=null'

Tested on Android, it works OK as before, but upgrading, UWP breaks on this error.

**Comment by peterfoot** [comment]
Latest v1 and v2 versions support up to Xamarin Forms 4.1
