### ISSUE TITLE
UWP 'System.StackOverflowException' in InTheHand.Forms.Platform.UWP.dll

### ISSUE THREAD

**Issue by jkalexander** [inthehand/InTheHand.Forms#31]
Hi, I absolutely love this package.  Has made showing videos very easy.

I am building a UWP, iOS, and Android application, and am running into a 'System.StackOverflowException' in InTheHand.Forms.Platform.UWP.dll error.

I am using Xamarin.Forms 2.4.0.282 (although have also tried with 2.4.0.280 and 2.5.0.91635) and am playing a video that is recorded from the camera.  I can confirm the video is "good" by playing it on my development machine via VLC media player.  It is maybe a 5 second video.

<inthehand:MediaElement x:Name="MediaPlayer"
						AreTransportControlsEnabled="False"
						AutoPlay="True"
						IsLooping="True"
						Stretch="UniformToFill"
						Source="{Binding VideoSource}"
						HorizontalOptions="CenterAndExpand"
						VerticalOptions="CenterAndExpand"/>

The video starts to play, the exception gets thrown about halfway through, but the video continues to play until the end.  Sometimes it looks like it begins the second playback (since looping is enabled), but then stops.

I've tested by disabling setting AutoPlay to false and manually starting, and setting IsLooping to false - no effect, I still get the exception.

If there is anything I can do to help, just let me know!  Or if you have any ideas of a work-around, that'd be helpful.

It would be nice if there was an exception delegate to catch and handle exceptions.

**Comment by peterfoot** [comment]
Fixed in 10.2017.1213
