### ISSUE TITLE
IOS : MediaElement not found in InTheHand.Forms

### ISSUE THREAD

**Issue by GreYak** [inthehand/InTheHand.Forms#37]
Hi, 

I am working with Xamarin.Forms 2.5.0.122203 and I meet the following mistake on IOS 11.2 ( when everything works perfectly on with Uwp and Android)  :
`
Xamarin.Forms.Xaml.XamlParseException: Position 8:10. Type inthehand:MediaElement not found in xmlns clr-namespace:InTheHand.Forms;assembly=InTheHand.Forms`

My xaml is the following : 
```
<?xml version="1.0" encoding="UTF-8"?>
<ContentPage xmlns="http://xamarin.com/schemas/2014/forms" 
             xmlns:x="http://schemas.microsoft.com/winfx/2009/xaml"
             xmlns:inthehand="clr-namespace:InTheHand.Forms;assembly=InTheHand.Forms"
             x:Class="Test.VideoPage">
    <StackLayout>
        <Label Text="Hello Xamarin.Forms!" />
        <inthehand:MediaElement
                 HorizontalOptions="Fill" VerticalOptions="Center" AutoPlay="True" 
                 HeightRequest="240" AreTransportControlsEnabled="true" 
                 Source="http://video.ch9.ms/ch9/334f/891b78a5-642d-40b4-8d02-ff40ffdd334f/LoginToLinkedinUSingXamarinAuth_mid.mp4"/>
    </StackLayout>
</ContentPage>
```

Do I something wrong ? Or is it bug in the API ?

Thanks by advance for your answer!
And thanks so much for the API ! 🥇

**Comment by peterfoot** [comment]
I've not seen that one before. Are you calling InTheHandForms.Init() in the AppDelegate during startup?

**Comment by GreYak** [comment]
No, i didn't...
After initializing, it seems being ok. Thanks a lot.

I didn't see before, that Init() has to be done in each project targeting specific platform.
Is there a way to unify this one into the common app ?

**Comment by peterfoot** [comment]
Sadly not currently - these init methods are in each platform specific library as they force Xamarin to register the renderers. There is a possibility that something like this might be possible when building the library but I haven't tried it yet - https://github.com/Fody/ModuleInit

**Comment by GreYak** [comment]
Ok, thank you so much for your answers and work, Peter ! :)
