### ISSUE TITLE
Can't load local MP4

### ISSUE THREAD

**Issue by jonathan-austen** [inthehand/InTheHand.Forms#38]
Your control works great if I load a video from the internet, but I want to load an MP4 video file that's embedded with my code. How do I set the Source? I've tried things like putting the MP4 in the Resources/drawable directory. I even created a raw directory under Resources and put as my Source="./raw/filename.mp4" but nothing.

**Comment by peterfoot** [comment]
For a file embedded in the package you can use the ms-appx uri scheme. On android this specifies a file placed in the resources/raw folder (ensure the Build Action is AndroidResource. e.g.
ms-appx:///Filename.mp4

**Comment by jonathan-austen** [comment]
Holy crap that worked. I've been searching for hours and then decided to ask. Thank you!!

**Comment by jonathan-austen** [comment]
So, this is my Xamarin forms .cs code. I'm guessing this snippet only works for Android. What do I have to do to make it work for iOS?

        protected override void OnAppearing()
        {
            Media.Source = new Uri("ms-appx:///GD_video_trimmed.mp4");
            if (Media.CurrentState != InTheHand.Forms.MediaElementState.Playing)
            {
                Media.Play();
            }
        }

**Comment by peterfoot** [comment]
No problem, it's my fault for not documenting it clearly because those uri schemes are borrowed from UWP development. On iOS you add the file as a BundleResource and the path is relative to the root of the project so your GD_video_trimmed.mp4 from the above example would go in the root folder of your iOS project with build action BundleResource.

**Comment by jonathan-austen** [comment]
Thanks. So I guess that means this line of code (Media.Source = new Uri("ms-appx:///GD_video_trimmed.mp4");) stays the same. You've been a huge help. Thank you for this project.

**Comment by jdausten97** [comment]
The video won't play in iOS. I just finally got a Mac machine to test it on. What's the URI path for Mac? Above you wrote "Media.Source = new Uri("ms-appx:///GD_video_trimmed.mp4");" but is that the path structure for Android only?

**Comment by jdausten97** [comment]
Never mind, I realized what's wrong. I checked your sample in iOS. I forgot to include this "InTheHand.Forms.Platform.iOS.InTheHandForms.Init();" in my AppDelegate.cs file
