### ISSUE TITLE
Video Freezes OnDisplay

### ISSUE THREAD

**Issue by jonathan-austen** [inthehand/InTheHand.Forms#39]
When I load the video on my MainPage.xaml page and leave, then come back to that page the video doesn't restart. The audio restarts, just not the video. Here, let me draw it out for you so it's clear.

When the page loads for the first time, the OnAppearing is fired and the video is loaded and begins playing. Everything is cool. The user clicks the page and it moves to another page at which point I pause the video via the OnDisappearing event, this way it's not running and making noise in the background. When the user returns to the MainPage the OnAppearing is triggered once again and the video starts all over, however the video image is stuck where it left off when it was stopped and now the sound is going with a frozen video.

        protected override void OnAppearing()
        {
            Media.Source = new Uri("ms-appx:///GD_video_trimmed.mp4");
            if (Media.CurrentState != InTheHand.Forms.MediaElementState.Playing)
            {
                Media.Play();
            }
        }

        protected override void OnDisappearing()
        {
            if (Media.CurrentState == InTheHand.Forms.MediaElementState.Playing)
            {
                Media.Stop();
            }
        }

**Comment by jonathan-austen** [comment]
I think I figured it out. If I set the Media.Source = NULL then when I return to the page the video starts all over.

        protected override void OnDisappearing()
        {
            if (Media.CurrentState == InTheHand.Forms.MediaElementState.Playing)
            {
                Media.Stop();
                Media.Source = null;
            }
        }

**Comment by jonathan-austen** [comment]
Nope. That didn't do it. Still freezes. Hmm. I thought for sure that would fix it.

**Comment by jonathan-austen** [comment]
Any idea why the video won't restart after it's been stopped?

**Comment by peterfoot** [comment]
All future MediaElement work will take place at https://github.com/xamarin/XamarinCommunityToolkit
