### ISSUE TITLE
Implement via C#

### ISSUE THREAD

**Issue by aftersow** [inthehand/InTheHand.Forms#40]
Hi there,

Trialing out the MediaElement to display a video via a code behind but don't seem to be having any luck. I couldn't find much about implementing besides XAML. Below is a snippet of my code. Currently the output is just a blank section where it should be (no errors or anything of note in the log)

```
var videoLayout = new StackLayout { VerticalOptions = LayoutOptions.Center, HorizontalOptions = LayoutOptions.Center };
var video = new MediaElement { HorizontalOptions = LayoutOptions.Fill, VerticalOptions = LayoutOptions.Fill, AreTransportControlsEnabled = true, Source = new Uri("http://video.ch9.ms/ch9/334f/891b78a5-642d-40b4-8d02-ff40ffdd334f/LoginToLinkedinUSingXamarinAuth_mid.mp4"), HeightRequest = 125 };
videoLayout.Children.Add(video);
detailGrid.Children.Add(videoLayout, 0, 2, rowCounter, ++rowCounter);
```

Any guidance would be great!

Thanks

**Comment by peterfoot** [comment]
If the control doesn't appear to be rendering anything check that in your device project you are calling the init method e.g.

iOS - AppDelegate FinishedLaunching
InTheHand.Forms.Platform.iOS.InTheHandForms.Init();

Android - MainActivity OnCreate
InTheHand.Forms.Platform.Android.InTheHandForms.Init();
