### ISSUE TITLE
AutoViewCell crashes on iOS

### ISSUE THREAD

**Issue by closetoyou293** [inthehand/InTheHand.Forms#44]
I used AutoViewCell code in iOS to show a list of post. Post contains image, text, comment, etc.
It crashes when I navigate to that screen in second time. Any idea?
`0x00000001027ffd10 0x00000001027e795c 0x0000000101918db8 0x0000000101965088 0x00000001018c2b68 0x0000000101233db8 0x00000001011701e8 0x000000010113a2c8 0x0000000101170118 0x000000010114a418 0x0000000101960ed8 0x00000001019862d8 0x0000000100fcc324 0x000000
*** Terminating app due to uncaught exception 'NSInternalInconsistencyException', reason: 'Invalid update: invalid number of rows in section 0. The number of rows contained in an existing section after the update (20) must be equal to the number of rows contained in that section before the update (10), plus or minus the number of rows inserted or deleted from that section (10 inserted, 10 deleted) and plus or minus the number of rows moved into or out of that section (0 moved in, 0 moved out).'`

**Comment by peterfoot** [comment]
I have seen this intermittently but don't know the cause yet

**Comment by closetoyou293** [comment]
Work around by clearing list before update item source. It seems problem comes from XF.
