### ISSUE TITLE
UWP Crash after upgrade

### ISSUE THREAD

**Issue by joseluisct** [inthehand/InTheHand.Forms#45]
After upgrading InTheHand.Forms Nuget package to 1.0.2018.111, the UWP app crashes trying to load MediaElement, with the exception:

`System.IO.FileNotFoundException: Could not load file or assembly 'InTheHand.Forms, Version=10.2018.0.0, Culture=neutral, PublicKeyToken=null'`

Tested on Android and it works OK as before, but UWP breaks on this error.

I've tested that error also happens with version 1.0.2018.110, but no with 1.0.2018.105 and lower versions.

I'm using Xamarin Forms version 2.5.0.280555 (latest stable), and Win10 Fall Creators Update.

**Comment by peterfoot** [comment]
Will look into this with an aim for fixing this week

**Comment by charlesroddie** [comment]
Also getting this issue.

**Comment by charlesroddie** [comment]
Any ideas @peterfoot ?

**Comment by peterfoot** [comment]
Sorry, this should now be resolved in 1.0.2018.423

**Comment by charlesroddie** [comment]
Thanks. The new version works for me.

**Comment by joseluisct** [comment]
Thanks. Also works for me :)
