### ISSUE TITLE
Video Won't Start on Android

### ISSUE THREAD

**Issue by jdausten97** [inthehand/InTheHand.Forms#46]
So, I have this working just fine on iOS. On Android, it won't work until I leave the page then come back to it. Here's my initial code to load the video. After that is the code that's called from the next page to return to the home page containing the video. I'll say that this used to work when I was developing on a Windows laptop but since switching to Visual Studio Mac it doesn't start.

******* MainPage Code *******

        public MainPage()
        {
            InitializeComponent();
            NavigationPage.SetHasNavigationBar(this, false);
            Media.Source = new Uri("ms-appx:///GD_video_trimmed.mp4");
            BindingContext = new MainPageViewModel(Navigation); 
        }

        protected override void OnAppearing()
        {
            ((MainPageViewModel)BindingContext).PopulateModel();

            if (Media.CurrentState != InTheHand.Forms.MediaElementState.Playing)
            {
                Media.Play();
            }

            SizeControls();
        }

****** Code called to return to MainPage and the Video starts then ******
        public static void ClearNavigationStack(INavigation navigation)
        {
            navigation.InsertPageBefore(new MainPage(), navigation.NavigationStack[0]);
            navigation.PopToRootAsync();           
        }

**Comment by peterfoot** [comment]
All future MediaElement work will take place at https://github.com/xamarin/XamarinCommunityToolkit
