### ISSUE TITLE
Cannot seek to start or end of MediaElement on iOS

### ISSUE THREAD

**Issue by j-sauer** [inthehand/InTheHand.Forms#47]
Setting the position of a MediaElement instance to a TimeSpan that represents 0 seconds does not work on iOS.
This is due to the implementation of IMediaElementRenderer.Seek in [MediaElementRenderer.](https://github.com/inthehand/InTheHand.Forms/blob/master/InTheHand.Forms/InTheHand.Forms.Platform.iOS/MediaElementRenderer.cs).
In line 368
`seekTo > v.CMTimeRangeValue.Start && seekTo < (v.CMTimeRangeValue.Start + v.CMTimeRangeValue.Duration))`
should be
`seekTo >= v.CMTimeRangeValue.Start && seekTo <= (v.CMTimeRangeValue.Start + v.CMTimeRangeValue.Duration))`
I guess.

**Comment by peterfoot** [comment]
Fixed in 1.0.2018.420
