### ISSUE TITLE
Getting or setting Position does nothing on UWP

### ISSUE THREAD

**Issue by charlesroddie** [inthehand/InTheHand.Forms#5]
On UWP, it is possible to get or set the position property but the property is unrelated to the state of the video.

Setting the position does not cause the video position to change, and the property does not change as the video is playing.

I have not tested on other platforms.

**Comment by charlesroddie** [comment]
Same on Windows 8.1

**Comment by peterfoot** [comment]
Fixed for UWP 1.0.2017.419. Keeping open for WinRT/wp81

**Comment by peterfoot** [comment]
Renderers are now shared, fixed across Windows

**Comment by mwpb** [comment]
On Win81/UWP:
Setting position seems to work, but it doesn't like to be set to the same position twice. Nothing happens in this case.
A workaround is to add a small random number when setting.
Can give minimal example if needed.
