### ISSUE TITLE
Video won't play in distribution ipa (iOS) 

### ISSUE THREAD

**Issue by XamarinOrem** [inthehand/InTheHand.Forms#50]
The video is playing properly on the iOS device and on the iOS simulator but when I made ipa to put it on either the test flight or on to the App Store, The video won't play. Tried with many video urls.

**Comment by peterfoot** [comment]
Hi, have you checked your info.plist is setup to allow content from the target domain - https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CocoaKeys.html#//apple_ref/doc/uid/TP40009251-SW33

**Comment by XamarinOrem** [comment]
![screen shot 2018-12-20 at 4 33 52 pm](https://user-images.githubusercontent.com/32254709/50281305-11ede980-0475-11e9-9674-5f3db21b01da.png)
These three properties are set to true in my info.plist

**Comment by peterfoot** [comment]
Ok, does the appdelegate call the init method to load the renderer - otherwise the control will just be a blank rectangle - 
InTheHand.Forms.Platform.iOS.InTheHandForms.Init();

**Comment by XamarinOrem** [comment]
Yes I did. The video is working in the development mode, But not in the distribution mode.
![screen shot 2018-12-20 at 4 37 17 pm](https://user-images.githubusercontent.com/32254709/50281501-a35d5b80-0475-11e9-9c49-f85b0849d88a.png)

**Comment by XamarinOrem** [comment]
Is there anything else that I need to set?

**Comment by peterfoot** [comment]
What are your linker settings for the release build? You may need to exclude InTheHand.Forms.dll and InTheHand.Forms.Platform.iOS.dll or set it to SDK assemblies only.

**Comment by XamarinOrem** [comment]
Yes it worked like a charm now! Thank you :)
