### ISSUE TITLE
the control doesn't appear in iOS

### ISSUE THREAD

**Issue by ghost** [inthehand/InTheHand.Forms#51]
I'm using Xamarin.forms 3.0 with VS 2017 ,My problem is  the control, it  doesn't appear when I test  the iOS plateform  even after I put "InTheHand.Forms.Platform.iOS.InTheHandForms.Init()" on the AppDelegate, Any help please ?
Thank you a lot :),

**Comment by peterfoot** [comment]
Check your linker settings, you may need to add the InTheHand.Forms and the platform dll to the exclusions list
