### ISSUE TITLE
Video can't play

### ISSUE THREAD

**Issue by mmehdidehghani** [inthehand/InTheHand.Forms#53]
Hi
I used Xamarin.Form (Xamarin.Forms v 3.3 - .Net Standard 2.0). I can't play my videos :(
I think the problem is video codec. my videos are libx264 from ffmpeg (mp4) and player can not play them :(
But when i  use this below sample, It works:
https://archive.org/download/BigBuckBunny_328/BigBuckBunny_512kb.mp4

I don't know that my question is correct or not: 
How can i set codec or install with my projct

**Comment by peterfoot** [comment]
The control uses the platform video player so for iOS this is AVMediaPlayerViewController and for Android the VideoView. It will support any codecs built into the OS. There is a reference here for Android:-
https://developer.android.com/guide/topics/media/media-formats#core
