### ISSUE TITLE
activity indicator doesnt disappear when video starts

### ISSUE THREAD

**Issue by dely17** [inthehand/InTheHand.Forms#59]
C#
        private void StopIndicator()
        {
            if (Mediaa.CurrentState != InTheHand.Forms.MediaElementState.Playing)
            {
                running.IsVisible= true;      
            }
            else if (Mediaa.CurrentState == InTheHand.Forms.MediaElementState.Playing)
            {
                running.IsVisible = false;
            }
        }

**Comment by peterfoot** [comment]
All future MediaElement work will take place at https://github.com/xamarin/XamarinCommunityToolkit
