### ISSUE TITLE
About video player in WPF

### ISSUE THREAD

**Issue by szsx12345** [inthehand/InTheHand.Forms#62]
Is it possible to add media player in WPF ?
I add         
<forms:MediaElement HorizontalOptions="Fill" BackgroundColor="White" VerticalOptions="Center" HeightRequest="240" x:Name="Media" IsLooping="True" ShowsPlaybackControls="True" Source="http://video.ch9.ms/ch9/334f/891b78a5-642d-40b4-8d02-ff40ffdd334f/LoginToLinkedinUSingXamarinAuth_mid.mp4"/>
in the view xaml file, but wpf still can't play vedio.

**Comment by peterfoot** [comment]
It's not currently completed and in the NuGet yet but should be available soon

**Comment by peterfoot** [comment]
This is now available in the latest (2.0.2019.913) release
