### ISSUE TITLE
Bind command in MediaElement

### ISSUE THREAD

**Issue by CYLMos** [inthehand/InTheHand.Forms#63]
I am using MvvmCross, and I want that when the media ends, I want to do some processes.
But I only found an event called "MediaEnd".
If I want to follow MVVM, I can't write the event method in xaml.cs.
Consequently, I need to implement a Command in MediaElement, but I don't have any idea how can I put it in.

Thanks!

**Comment by CYLMos** [comment]
I think I solved it.
I ignored a property called CurrentState.
I used it to bind my property by OneWayToSource mode, and realize my process.

**Comment by peterfoot** [comment]
Great, glad this works for your scenario!
