### ISSUE TITLE
Is there any way to keep the controls visible all the time?

### ISSUE THREAD

**Issue by gogolon** [inthehand/InTheHand.Forms#65]
Hello. I'm creating an app that involves playing audio files. That NuGet seems to suit my needs, but I can't find any property that could prevent the controls from hiding. I'd like them to be visible all the time, not only when user clicks the area of the control. Is it possible?

**Comment by peterfoot** [comment]
Not currently but I'll look into it.

**Comment by gogolon** [comment]
If anyone else is still in need of this feature, you can now achieve that by using Xamarin.Forms experimental MediaElement and setting up your own controls.

**Comment by peterfoot** [comment]
All future MediaElement work will take place at https://github.com/xamarin/XamarinCommunityToolkit
