### ISSUE TITLE
TimeSpan does not accept floating point Not-a-Number values. on iOS

### ISSUE THREAD

**Issue by Liminiens** [inthehand/InTheHand.Forms#66]
When loading a local video with `file://` Uri on Android everything is fine, but on iOS `**System.ArgumentException:** 'TimeSpan does not accept floating point Not-a-Number values.'` is thrown.

Maybe problem is [here](https://github.com/inthehand/InTheHand.Forms/blob/master/InTheHand.Forms/InTheHand.Forms.Platform.iOS/MediaElementRenderer.cs#L292)?

**Comment by peterfoot** [comment]
Thanks, looking into this now.

**Comment by Liminiens** [comment]
@peterfoot this fixed the crush, thank you! Unrelated to original issue, but now there is a black screen instead of video, maybe because `file://` uris (`AbsoluteUrl` is passed to NSUrl constructor which contains `file://` prefix) are not handled correctly by `NSUrl` [here](https://github.com/inthehand/InTheHand.Forms/blob/master/InTheHand.Forms/InTheHand.Forms.Platform.iOS/MediaElementRenderer.cs#L128)

**Comment by peterfoot** [comment]
Is your file:// uri an absolute path or relative to your app? You can also use the ms-appx:// scheme for a bundle resource or ms-appdata for a local or temp file path.

**Comment by Liminiens** [comment]
Yes, it’s an absolute path and I will try ms-appx tomorrow:)

**Comment by Liminiens** [comment]
Hm... `ms-appx://` and `ms-appdata://` didn't work. I think we should close this issue and I will try to investigate if problem with black screen is on our side or not. Thank you!

**Comment by peterfoot** [comment]
For example for a bundle resource in iOS or raw resource in Android you can use ms-appx:///myfile.mp4
For a local file saved into the apps local storage (documents in iOS) ms-appdata://local/myfile.mp4
For a file saved to the temporary directory ms-appdata://temp/myfile.mp4

**Comment by peterfoot** [comment]
Hi @Liminiens any update on this or should I close this issue for now?

**Comment by Liminiens** [comment]
@peterfoot sorry for late reply! Right now, on iOS files are stored in `Library` subdirectories, like `.../Library/<folder name>/<video name>`. With ms-appadata i tried `ms-appdata:///local/<folder name>/<video name>` but that didn't work.

**Comment by peterfoot** [comment]
All future MediaElement work will take place at https://github.com/xamarin/XamarinCommunityToolkit
