### ISSUE TITLE
Does the Volume Property work on Andriod?

### ISSUE THREAD

**Issue by Todd442** [inthehand/InTheHand.Forms#67]
Love the work! Love the MediaElement but Volume property doesn't appear to work?

I've been assuming 1 = 100% and .5 = 50%. But the values I place in the property seem to have no effect. 

What's missing?

**Comment by peterfoot** [comment]
It should be working. What kind of device are you testing on and which Android version?

**Comment by Todd442** [comment]
Android 9 API 28 on a Samsung Galaxy S8.

**Comment by peterfoot** [comment]
All future MediaElement work will take place at https://github.com/xamarin/XamarinCommunityToolkit
