### ISSUE TITLE
Xamarin.iOS native crash _avPlayerViewController.Player.Pause();

### ISSUE THREAD

**Issue by tekmun** [inthehand/InTheHand.Forms#69]
After upgrading to Xamarin.Forms 4.8, I encoutered crashes randomly whenever _avPlayerViewController.Player is paused. The Output window contains many rows of these outputs:

 8          124
00000046:  0128  3          2            3
00000052:  0131  2         12          132
0000005E:  0132  2         20          144
000000A6:  0100  4          4          256
000000B2:  0101  4          4          180
000000BE:  0102  3          6          266
000000CA:  0103  3          2            6
000000D6:  0106  3          2            6
000000E2:  0115  3          2            3
000000EE:  0201  4          4          272
000000FA:  0202  4          4         3475
0000000A:  0100  4          4           68
00000016:  0101  4          4           48
00000022:  0102  3          6          110
0000002E:  011A  5          8          116
0000003A:  011B  5          8          124
00000046:  0128  3          2            3
00000052:  0131  2         12          132
0000005E:  0132  2         20          144
000000A6:  0100  4          4          256
000000B2:  0101  4          4          180
000000BE:  0102  3          6          266
000000CA:  0103  3          2            6
000000D6:  0106 
 3          2            6
000000E2:  0115  3          2            3
000000EE:  0201  4          4          272
000000FA:  0202  4          4         3665
0000000A:  0100  4          4           68
00000016:  0101  4          4           48
00000022:  0102  3          6          110
0000002E:  011A  5          8          116
0000003A:  011B  5          8          124
00000046:  0128  3          2            3
00000052:  0131  2         12          132
0000005E:  0132  2         20          144
000000A6:  0100  4          4          256
000000B2:  0101  4          4          180
000000BE:  0102  3          6          266
000000CA:  0103  3          2            6
000000D6:  0106  3          2            6
000000E2:  0115  3          2            3
000000EE:  0201  4          4          272
000000FA:  0202  4          4         4269
0000000A:  0100  4          4           88
00000016:  0101  4          4           88
00000022:  0102  3          6          110
0000002E:  011A  5          8          116
0000003A

If I have waited for more than 10 seconds, the resume playback works fine. Occasionally, immediate playback works too. Unfortunately, immediate playback crashes the app.

Any suggestion is appreciated. Thanks.

**Comment by peterfoot** [comment]
All future MediaElement work will take place at https://github.com/xamarin/XamarinCommunityToolkit
