### ISSUE TITLE
Do it support tap gesture?

### ISSUE THREAD

**Issue by biapar** [inthehand/InTheHand.Forms#7]
Hi,

I tried the code:
                                    var tapGestureRecognizer = new TapGestureRecognizer();
                                    tapGestureRecognizer.Tapped += OnTapGestureRecognizerTapped;
                                    myvideo.GestureRecognizers.Add(tapGestureRecognizer);

but the event is not fired.
Do it support the tap event?

**Comment by peterfoot** [comment]
I don't think this is currently supported because the native video element listens for taps to play/pause the video. I will need to investigate if there is a workaround.

**Comment by biapar** [comment]
Hi, I tried to remove the custom tap gesture, but if I tap on video, it do not start.

**Comment by peterfoot** [comment]
This will require some extra work and possibly a method to enable/disable it.

**Comment by peterfoot** [comment]
All future MediaElement work will take place at https://github.com/xamarin/XamarinCommunityToolkit
