### ISSUE TITLE
Android: Stretch.Fill doesn't stretch - Aspect ratio is always enforced

### ISSUE THREAD

**Issue by peterfoot** [inthehand/InTheHand.Forms#9]
For consistency with other platforms this value should stretch the video to fill the Element even if the aspect ratio is different causes it to change the proportions of the video.

**Comment by dationguyen** [comment]
I have the same concern about UniformToFill option.

**Comment by peterfoot** [comment]
What's the problem with UniformToFill? This preserves aspect ratio and expands to fill the container, cropping if necessary.

**Comment by dationguyen** [comment]
Hi Peter,
The below picture is what I have with UniformToFill. I expect to let it fill the frame but not change the ratio.
![screenshot_20171120-225333](https://user-images.githubusercontent.com/26321444/33017354-30ec1214-ce46-11e7-81a3-1da935d14f9f.png)

Best regards,
Datio Nguyen

**Comment by peterfoot** [comment]
All future MediaElement work will take place at https://github.com/xamarin/XamarinCommunityToolkit
